#!/bin/sh                                                                                                                                                                                    
alias j='z'                                                                                                                                                                                  
alias f='zi'                                                                                                                                                                                 
alias g='lazygit'                                                                                                                                                                            
alias gs'git status'                                                                                                                                                                            
alias vim='nvim'                                                                                                                                                                             
alias vi='nvim'                                                                                                                                                                              
alias tm='tmux attach'                                                                                                                                                                              
alias dnf='sudo dnf'                                                                                                                                                                         
alias apt='sudo apt'                                                                                                                                                                         
alias pacman='sudo pacman'                                                                                                                                                                         
# alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"                                                          
alias nvimrc='nvim ~/.config/nvim/'

# get fastest mirrors
# alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
# alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
# alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
# alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# Remarkable
# alias remarkable_ssh='ssh root@10.11.99.1'
# alias restream='restream -p'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5' 
# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5' 

# systemd
alias systemctlenabled="systemctl list-unit-files --state=enabled"

if [[ $TERM == "xterm-kitty" ]]; then
  alias ssh="kitty +kitten ssh"
fi

case "$(uname -s)" in

Darwin)
        # echo 'Mac OS X'
        ;;

Linux)
        alias ls='exa --icons'
        alias la='/bin/ls -laZ --color'
        alias ll='exa -lahgHGd'
        ;;

CYGWIN* | MINGW32* | MSYS* | MINGW*)
        # echo 'MS Windows'
        ;;
*)
        # echo 'Other OS'
        ;;
esac
