#!/bin/sh
export HISTFILE=~/.config/zsh/history
export HISTSIZE=10000
export SAVEHIST=10000
export MANPAGER='nvim +Man!'
export MANWIDTH=999
setopt append_history
setopt extended_history
setopt inc_append_history

export VISUAL="/usr/bin/nvim"
export EDITOR="/usr/bin/nvim"

export PATH="$HOME/.local/bin":$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go
export GOBIN=$HOME/.local/share/go/bin
export PATH=$HOME/.cargo/bin:$PATH
export RUSTPATH=$HOME/.cargo/env

export EXA_COLORS='di=1;36:da=1;36'

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
# __conda_setup="$("$HOME/.miniconda/bin/conda" 'shell.zsh' 'hook' 2> /dev/null)"
# if [ $? -eq 0 ]; then
#     eval "$__conda_setup"
# else
#     if [ -f "$HOME/.miniconda/etc/profile.d/conda.sh" ]; then
#         . "$HOME/.miniconda/etc/profile.d/conda.sh"
#     else
#         export PATH="$HOME/.miniconda/bin:$PATH"
#     fi
# fi
# unset __conda_setup
# <<< conda initialize <<<#!/bin/sh
#
