
input {
    kb_layout=hu,gb
    kb_variant =
    kb_model =
    kb_options = grp:win_space_toggle
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = yes
    }

    #sensitivity = -0.7 # -1.0 - 1.0, 0 means no modification.
    sensitivity = 0.2 # -1.0 - 1.0, 0 means no modification.
}


