# Курсор
env = XCURSOR_SIZE,24
## NVIDIA
#env = LIBVA_DRIVER_NAME,nvidia
#env = XDG_SESSION_TYPE,wayland
#env = GBM_BACKEND,nvidia-drm
#env = __GLX_VENDOR_LIBRARY_NAME,nvidia
#env = WLR_NO_HARDWARE_CURSORS,1
#env = NVD_BACKEND,direct
# FIREFOX
env = MOZ_DISABLE_RDD_SANDBOX,1
env = EGL_PLATFORM,wayland
env = MOZ_ENABLE_WAYLAND,1
# Нужно для qt приложений
env = QT_QPA_PLATFORM,wayland
# Нужно для qt темы
env = QT_QPA_PLATFORMTHEME,qt5ct

misc {
  enable_swallow = true
  swallow_regex = ^(Alacritty|kitty|footclient)$
}


general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 5
    gaps_out = 5
    border_size = 1
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)

    layout = dwindle
}

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
}

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    # new_is_master = true
}

gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    # workspace_swipe = off
}
