# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# windowrule=float,^(kitty)$
# windowrule=move 0 0,title:^(Firefox)(.*)$
windowrulev2 = opacity 0.95,class:^(kitty)$
# windowrule = float, class:kitty, title:kitty
windowrulev2 = workspace 9, class:^(discord)$
windowrulev2 = workspace 8, class:^(steam)$
windowrulev2 = workspace 7, class:^(thunderbird)$
windowrulev2 = float, initialTitle: Picture-in-Picture
windowrulev2 = pin, initialTitle: Picture-in-Picture
windowrulev2 = size 600 330, initialTitle: Picture-in-Picture
windowrulev2 = move 1955 35, initialTitle: Picture-in-Picture
windowrulev2 = noinitialfocus, initialTitle: Picture-in-Picture


# Workspace fixing to big monitor
workspace = 9,monitor:desc:Samsung Display Corp. 0x414A,decorate:true,gapsin:0,gapsout:0
workspace = 9,monitor:desc:Samsung Display Corp. 0x414A,decorate:true,gapsin:0,gapsout:0
workspace = 1,monitor:desc:Samsung Electric Company Odyssey G5 HNBY500117,decorate:true
workspace = 2,monitor:desc:Samsung Electric Company Odyssey G5 HNBY500117,decorate:true
workspace = 3,monitor:desc:Samsung Electric Company Odyssey G5 HNBY500117,decorate:true
workspace = 4,monitor:desc:Samsung Electric Company Odyssey G5 HNBY500117,decorate:true
